site/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions_controller/create'

  get 'sessions_controller/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :appointments
  get 'appointments' => "appointments#index"

  get 'appointments/create'

  get 'appointments/update'

  get 'appointments/destroy'

  get 'main/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  get 'contact', to: 'main#contact'

end

site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

site/app/models/appointment.rb
class Appointment < ApplicationRecord
  before_save :default_values
  def default_values
    self.userName ||= 'Teej'
  end
end

site/app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def index
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

site/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:start_time, :end_time)
    end
end

site/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def appointments

  end

  def contact
    
  end
end

site/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

site/app/helpers/application_helper.rb
module ApplicationHelper
end

site/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

site/app/helpers/main_helper.rb
module MainHelper
end

site/app/helpers/sessions_helper.rb
module SessionsHelper
end

site/app/views/appointments/_form.html.erb
<%= form_for(appointment) do |f| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site/app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

site/app/views/appointments/destroy.html.erb
<h1>Appointments#destroy</h1>
<p>Find me in app/views/appointments/destroy.html.erb</p>

site/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

site/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="page-header text-center">Appointments</h1>
<div class="row">
  <div class="col-lg-10 col-lg-offset-1 calendar-container">


    <%= month_calendar events: @appointments do |date, appointments| %>
    <%= date %>

  <% appointments.each do |appointment| %>
    <div>
      <%= appointment.userName %>
    </div>
  <% end %>
  <% end %>
  <div class="text-center">
    <%= link_to 'New Appointment', new_appointment_path, {:class=>"btn btn-primary"} %>

  </div>
  </div>
</div>

<br>

site/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

site/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

site/app/views/appointments/update.html.erb
<h1>Appointments#update</h1>
<p>Find me in app/views/appointments/update.html.erb</p>

site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
      <link href="https://fonts.googleapis.com/css?family=Allura" rel="stylesheet">

<script src="https://unpkg.com/react@15/dist/react-with-addons.js"></script>
<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
  </head>

  <body class="rgba-secondary-2-1-bg" id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top" style="font-family: 'Allura', cursive">KatieMarie Photography</a>
                <a class="page-scroll" href="#about"><button id="specials_button" type="button" class="btn btn-warning">*Advertise specials here! </button></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#myCarousel">Home</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#gallery">Gallery</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                      <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <% if current_user %>
                    <li>
                      <a class="page-scroll" href="/appointments"><i class="fa fa-calendar" aria-hidden="true"> </i> My Appointments</a>
                    </li>
                    <li>
                      <p class="navbar-text"><%= current_user.name %></p>
                    </li>
                    <li>
                      <%= link_to "Sign out", signout_path, id: "sign_out" %>
                    </li>
                    <% else %>
                    <li>
                      <a class="btn btn-block btn-social btn-facebook" href="/auth/facebook">
                        <span class="fa fa-facebook"></span> Sign in with Facebook
                      </a>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <%= yield %>
  </body>
</html>

site/app/views/main/contact.html.erb
<div class="container" style="background-color:rgba(0, 0, 0, 0.6); color:white">

<div class="text-center">
  <h1 class="page-header">
    Contact Me
  </h1>
  <img class="img img-circle" height="200px" width="200px" src="https://scontent.fsnc1-1.fna.fbcdn.net/v/t1.0-9/14900411_1746767505573506_3007451679917616629_n.jpg?oh=1cf5026b40372c735551d8f7cbf3deb5&oe=58885E08" alt="" />
</div>
<div class="row text-center">
  <div class="col-md-5 col-md-push-1">
    <h2 class="page-header">Social Media:</h2>
    <ul class="" style="list-style:none">
      <li>
        <a class="btn btn-block btn-social btn-facebook" href="https://www.facebook.com/profile.php?id=100007208202295">
          <span class="fa fa-facebook"></span> fb:Katie Marie
        </a>
    </li>
      <li>
        <a class="btn btn-block btn-social btn-twitter" href="#">
          <span class="fa fa-twitter"></span> @Katie_marie
        </a>
      </li>
      <li>
        <a class="btn btn-block btn-social btn-instagram" href="#">
          <span class="fa fa-instagram"></span> @Katie_marie
        </a>
      </li>
    </ul>
  </div>
  <div class="col-md-5 col-md-push-1">
    <h2 class="page-header">Email me!</h2>
<!-- CONTACT FORM IN PROGRESS, GET INFO FROM FB AUTH IF LOGGED IN -->
<small> *In progress, info will auto pop from FB login/User login. What info do we need here?</small>
<!-- Remove <small> tags -->
    <form class="well form-horizontal" action=" " method="post"  id="contact_form">
<fieldset>

<!-- Form Name -->
<legend style="color:white">Have any suggestions or questions for me? Please fill out the form below!</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">First Name</label>
  <div class="col-md-8 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="fa fa-user"></i></span>
  <input  name="first_name" placeholder="First Name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Last Name</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="fa fa-user"></i></span>
  <input name="last_name" placeholder="Last Name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">E-Mail</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
  <input name="email" placeholder="E-Mail Address" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Phone #</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-phone"></i></span>
  <input name="phone" placeholder="(845)555-1212" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Address</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-home"></i></span>
  <input name="address" placeholder="Address" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">City</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-home"></i></span>
  <input name="city" placeholder="city" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Select Basic -->

<div class="form-group">
  <label class="col-md-4 control-label">State</label>
    <div class="col-md-8 selectContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-list"></i></span>
    <select name="state" class="form-control selectpicker" >
      <option value=" " >Please select your state</option>
      <option>Alabama</option>
      <option>Alaska</option>
      <option >Arizona</option>
      <option >Arkansas</option>
      <option >California</option>
      <option >Colorado</option>
      <option >Connecticut</option>
      <option >Delaware</option>
      <option >District of Columbia</option>
      <option> Florida</option>
      <option >Georgia</option>
      <option >Hawaii</option>
      <option >daho</option>
      <option >Illinois</option>
      <option >Indiana</option>
      <option >Iowa</option>
      <option> Kansas</option>
      <option >Kentucky</option>
      <option >Louisiana</option>
      <option>Maine</option>
      <option >Maryland</option>
      <option> Mass</option>
      <option >Michigan</option>
      <option >Minnesota</option>
      <option>Mississippi</option>
      <option>Missouri</option>
      <option>Montana</option>
      <option>Nebraska</option>
      <option>Nevada</option>
      <option>New Hampshire</option>
      <option>New Jersey</option>
      <option>New Mexico</option>
      <option>New York</option>
      <option>North Carolina</option>
      <option>North Dakota</option>
      <option>Ohio</option>
      <option>Oklahoma</option>
      <option>Oregon</option>
      <option>Pennsylvania</option>
      <option>Rhode Island</option>
      <option>South Carolina</option>
      <option>South Dakota</option>
      <option>Tennessee</option>
      <option>Texas</option>
      <option> Uttah</option>
      <option>Vermont</option>
      <option>Virginia</option>
      <option >Washington</option>
      <option >West Virginia</option>
      <option>Wisconsin</option>
      <option >Wyoming</option>
    </select>
  </div>
</div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Zip Code</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-home"></i></span>
  <input name="zip" placeholder="Zip Code" class="form-control"  type="text">
    </div>
</div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label">Website or domain name</label>
   <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-globe"></i></span>
  <input name="website" placeholder="Website or domain name" class="form-control" type="text">
    </div>
  </div>
</div>

<!-- radio checks -->
 <div class="form-group">
                        <label class="col-md-4 control-label">Do you have hosting?</label>
                        <div class="col-md-8">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="hosting" value="yes" /> Yes
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="hosting" value="no" /> No
                                </label>
                            </div>
                        </div>
                    </div>

<!-- Text area -->

<div class="form-group">
  <label class="col-md-4 control-label">Project Description</label>
    <div class="col-md-8 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
        	<textarea class="form-control" name="comment" placeholder="Project Description" style="width:100% !important"></textarea>
  </div>
  </div>
</div>

<!-- Success message -->
<!-- <div class="alert alert-success" role="alert" id="success_message">Success <i class="fa fa-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.</div> -->

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-8">
    <button type="submit" class="btn btn-warning" >Send <span class="fa fa-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
  </div>


</div>
</div>

site/app/views/main/index.html.erb
<div id="page-top" class="container container-fluid" style="width:100%">
<div class="row">
  <div class="col-lg-12">
      <div id="title" class="col-lg-8 col-lg-push-2" style="margin-top:10%">
          <div class="text-center">
            <span class="overline"></span>
            <a style="font-family: 'Allura', cursive; font-size: 10vh">KatieMarie Photography</a>

            <span class="underline"></span>
          </div>
      </div>
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div id="spacer">

        </div>
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item fill active slide-1">
          <div class="container">
            <div class="carousel-caption">
              <h1>Wedding Example</h1>
              <p>"Oh Em Gee, Katie was SUCH A GREAT PHOTOGRAPHER for our wedding, she's the best. I'm so happy we booked her [:" - Some Customer.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item fill slide-2">
          <div class="container">
            <div class="carousel-caption">
              <h1>Family Photo Example.</h1>
              <p>"Oh Em Gee, Katie was SUCH A GREAT PHOTOGRAPHER for our Family photos, even though our family is just me and my dog Panda, she did the BEST job taking pictures of him, I'm so happy we booked her [:" - Some Customer.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item fill slide-3">
          <div class="container">
            <div class="carousel-caption">
              <h1>Senior Picture Example.</h1>
              <p>"Oh Em Gee, Katie was SUCH A GREAT PHOTOGRAPHER for my Senior photos, I just HAVE to Tweet her to all mah franz, I'm so happy I booked her [:" - Some Customer.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="fa fa-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="fa fa-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
    <div id="spacer"></div>

    <div class="text-center guide-arrow" style="color: white; vertical-align:bottom">
      <a class="page-scroll" href="#gallery">
        <span class="fa fa-chevron-down"></span>
      </a>

    </div>




  </div>
  <div id="gallery" class="col-lg-10 col-lg-push-1">
    <div id="spacer"></div>
    <div class="row">
      <%= react_component("Gallery") %>

    </div>

    <div class="text-center guide-arrow" style="position:absolute;bottom:0; left:50%">
      <a class="page-scroll" href="#about"  style="color:black !important;">
        <span class="fa fa-chevron-down"></span>
      </a>
    </div>

  </div>
  <div id="about" class="col-lg-10 col-lg-push-1">
    <div id="spacer"></div>
    <%= react_component("About") %>

    <div class="text-center guide-arrow" style="position:absolute;bottom:0; left:50%">
      <a class="page-scroll" href="#contact">
        <span class="fa fa-chevron-down"></span>
      </a>
    </div>
  </div>
  <div id="contact" class="col-lg-10 col-lg-push-1">
    <div id="spacer"></div>
    <%= react_component("Contact") %>
  </div>

</div>
</div>

site/app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

site/app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading text-center">
    <%= link_to t('simple_calendar.previous', default: '<i class="fa fa-chevron-left"></i>'.html_safe), calendar.url_for_previous_view, {:class=>"btn btn-primary"} %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '<i class="fa fa-chevron-right"></i>'.html_safe), calendar.url_for_next_view, {:class=>"btn btn-primary"} %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

site/app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>